server {
    listen 80;
    server_name _;

    location /frontend {
        root /usr/share/nginx/html;  # Use root instead of alias to serve from the base directory
        try_files $uri $uri/ /index.html;  # Serve index.html for SPA routing
    }

    location /frontend/static {
        root /usr/share/nginx/html;  # Serve static files from the base directory
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }

    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "DENY";
    add_header X-XSS-Protection "1; mode=block";
}